  - name: Update Ubuntu Package Cache
    apt:
      update_cache: yes
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Resolving dpfg Issue
    command: sudo dpkg --configure -a
    when: ansible_distribution == "Ubuntu"
    async: 3600
    poll: 0

  - name: Waiting(pause) for dpkg to complete
    pause:
      seconds: 10
    when: ansible_distribution == "Ubuntu"

  - name: Install Nagios in Ubuntu
    apt:
      name: nagios4-core
      state: present
    when: ansible_distribution == "Ubuntu"
    async: 3600
    poll: 0

